import Head from "next/head";
import {
  Inter,
  Poppins,
  Playfair_Display,
  Playfair_Display_SC,
} from "next/font/google";
import Navbar from "@/Components/Navbar";
import Hero from "@/Components/HeroSection/Hero";
import data from "../../../public/data.json";
import Footer from "@/Components/Footer/Footer";
import HowItWork from "@/Components/Button/HowItWork/HowItWork";
const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "600"],
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display_SC({
  variable: "--font-playfair-display-sc",
  weight: ["400", "700", "900"],
  subsets: ["latin"],
});

const homeBanner = {
  herosection: {
    title: "Create in Plan",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since .",
    buttontext: "",
  },
};

export default function Home() {
  const backgroundColor = "#252C34";
  const textColor = "#FFFFFF";
  const isVisible = false;
  const paragrphColr = "#E4E4E4";
  return (
    <>
      <Head>
        <title>CoffeeRoaster inner page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${poppins.variable} ${playfairDisplay.variable}`}>
        <Navbar />
        <Hero data={homeBanner.herosection} />
        <HowItWork
          backgroundcolor={backgroundColor}
          textColor={textColor}
          isVisible={isVisible}
          paragrphColr={paragrphColr}
        />
        <Footer />
      </main>
    </>
  );
}
