import Head from "next/head";
import { Inter, Poppins } from "next/font/google";
import Navbar from "@/Components/Navbar";
import Hero from "@/Components/HeroSection/Hero";
const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ weight: ["400", "600"], subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>CoffeeRoaster</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={poppins.className}>
        <Navbar />
        <Hero />
      </main>
    </>
  );
}
